name: Benchmark
on:
  push:
    branches: [ master, new-gobenchdata ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: gobenchdata to gh-pages
      uses: bobheadxi/gobenchdata@v1
      with:
        PUBLISH: true
        PUBLISH_BRANCH: gh-pages
        SUBDIRECTORY: ./benchmarks
        PRUNE_COUNT: 40
        GO_TEST_FLAGS: -cpu 1,2
        BENCHMARKS_OUT: benchmarks/benchmarks.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
